# Generated by Django 5.0.4 on 2024-04-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('crissingname', models.CharField(max_length=50)),
                ('wereda', models.CharField(max_length=50)),
                ('kebele', models.CharField(max_length=50)),
                ('mothername', models.CharField(max_length=50)),
            ],
        ),
    ]
